apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    labels:
      app: {{ include "tekton-101-ocp.fullname" . }}
    name: {{ .Values.serviceName | quote }}
    namespace: {{ .Values.namespace | quote }}
  spec:
    ports:
    - name: http-tcp
      port: {{ .Values.port }}
      protocol: TCP
      targetPort: {{ .Values.port }}
    selector:
      app: {{ include "tekton-101-ocp.fullname" . }}
      deploymentconfig: {{ .Values.projectName | quote }}
    sessionAffinity: None
    type: ClusterIP
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    annotations:
      openshift.io/host.generated: "true"
    labels:
      app: {{ include "tekton-101-ocp.fullname" . }}
    name: {{ .Values.projectName | quote }}
    namespace: {{ .Values.namespace | quote }}
  spec:
    port:
      targetPort: http-tcp
    to:
      kind: Service
      name: {{ .Values.serviceName | quote }}
      weight: 100
    wildcardPolicy: None
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
