# Default values for tekton-101-ocp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

projectName: tekton-101
serviceName: tekton-101-v1
version: latest
port: 5000
memoryLimit: 256Mi
source:
  repository:
    url: https://github.com/haf-tech/tekton-101
    ref: master
    contextDir:
    webHookSecret: 

namespace: test-tekton101-iter8

# Istio configuration
istio:
 # Enable annotation to allow sidecar injection
 enableAnnotation: true



