---
# Creates a pipeline to build and update a nodejs application
# Referencing tasks from the OpenShift 4 Pipeline catalog:
# s2i-nodejs: to build, package and push
# custom-general-deploy: to deploy the application using the manifest definitions from the repo
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: nodejs-build-deploy
spec:
  # ###### Configuration
  resources:
  - name: git-repo
    type: git
  - name: image
    type: image
  params:
  - name: nodejs-version
    type: string
    description: nodejs version, default 10
    default: '10'
  - name: k8s_manifests
    type: string
    description: project deployment manifest directory
    default: "k8s"
  # ###### Tasks 
  tasks:
  - name: nodejs-build-image
    taskRef:
      name: s2i-nodejs
      kind: ClusterTask
    # set the expected resources and parameters of the task
    resources:      
      inputs:      
      - name: source
        resource: git-repo
      outputs:
      - name: image
        resource: image
    params:
    # verify TLS on the registry endpoint
    - name: TLSVERIFY
      value: "false" 
    # nodejs version
    - name: VERSION
      value: "$(params.nodejs-version)"
  - name: debug
    taskRef:
      name: debug
      kind: Task
    resources:      
      inputs:      
      - name: source
        resource: git-repo 
    runAfter:
    - nodejs-build-image
  - name: custom-general-deploy
    taskRef:
      name: openshift-cli
      kind: Task
    resources:      
      inputs:      
      - name: source
        resource: git-repo  
    params:       
    - name: ARGS
      value: 
      - "apply"
      - "-f"
      - $(params.k8s_manifests)
    runAfter:
    - nodejs-build-image